# Generated by Django 4.2.3 on 2023-07-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summuray',
        ),
        migrations.AddField(
            model_name='book',
            name='summury',
            field=models.TextField(blank=True, default='RAS'),
        ),
        migrations.AlterField(
            model_name='author',
            name='wikipedia',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
