# Generated by Django 4.2.3 on 2023-07-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_book_summuray_book_summury_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='summury',
            new_name='summary',
        ),
    ]
