# Generated by Django 4.2.3 on 2023-08-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rotation_period', models.CharField(max_length=10)),
                ('orbital_period', models.CharField(max_length=10)),
                ('diameter', models.CharField(max_length=10)),
                ('climate', models.CharField(max_length=100)),
                ('gravity', models.CharField(max_length=100)),
                ('terrain', models.CharField(max_length=100)),
                ('surface_water', models.CharField(max_length=10)),
                ('population', models.CharField(max_length=20)),
            ],
        ),
    ]
